pull_request_rules:
  - name: automatic merge
    conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=manual merge
      - "status-success=Travis CI - Branch "
    actions:
      merge:
        strict: "smart"
        method: rebase
