language: python
python:
  - '3.8'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="config.settings.local"

services:
  - postgresql

script:
  - ./manage.py test
  - black . --check
  - isort . --check
