language: python
python:
  - '3.9'

env: DJANGO_SETTINGS_MODULE="config.settings.ci"

services:
  - postgresql

before_install:
  - pip install -U pip
  - pip --version

install:
  - pip install tox

script:
  - tox
