# Generated by Django 3.1.2 on 2020-11-01 18:50

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_auto_20200726_2015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="code",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(13)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_small_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=100, validators=[django.core.validators.MinLengthValidator(2)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="nutriscore_grade",
            field=models.CharField(
                max_length=1, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="url",
            field=models.URLField(),
        ),
    ]
