name: CD

on:
  push:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        chmod 777 ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/github
        chmod 600 ~/.ssh/github
    - name: Deploy to production
      run: |
        ssh -v -i ~/.ssh/github -tto StrictHostKeyChecking=no guillaume@167.172.169.38 \
        "cd /home/guillaume/pur-beurre-p11 && git pull --rebase && /home/guillaume/.pyenv/shims/tox -e prod && exit"
